version: "3"

volumes:
  mysql_data:

services:
  #db
  mysql:
    hostname: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=recipe_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=MysqlPassword@10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      bash -c "python check_db.py --service-name mysql --ip mysql --port 3306 &&
      python manage.py migrate &&
      python manage.py runserver 0:8000"
    environment:
      - DB_HOST=mysql
      - DB_NAME=recipe_db
      - DB_USER=dev
      - DB_PASS=dev
    depends_on:
      - mysql
    expose:
      - 8000

  #nginx
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend

  # message broker
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  celery_worker:
    build:
      context: .
    command: celery -A app worker -l DEBUG
    depends_on:
      - backend
      - redis
      - mysql
