# Generated by Django 4.0.8 on 2022-11-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_ingredient_name_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_to_cook',
        ),
    ]
