# Generated by Django 4.0.8 on 2022-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_avg_price_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe.tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
