# Generated by Django 4.0.8 on 2023-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_avg_price_recipe_ingredients_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
